# Generated by Django 2.2.6 on 2020-10-09 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20201009_0100'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow_pair',
        ),
    ]
